apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html-config
data:
  index.html: |
    <html>
      <body style="background-color: {{ .Values.appParams.bgColor }}; text-align: center; padding: 50px; font-family: Arial;">
        <h1>{{ .Values.appParams.greeting }}</h1>
        <p>Version: {{ .Values.appParams.version }}</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.appParams.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: web-server
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: {{ .Release.Name }}-html-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80