services:
  web:
    # 1. Использование тегов latest
    image: nginx:latest
    # 2. Отсутствие restart policy (при ошибке контейнер просто умрет)
    ports:
      - "8080:80"
    # 3. Нет ограничений по ресурсам
    # 4. Нет зависимости от базы (depends_on). Web запустится до того, как БД будет готова

  db:
    image: postgres:latest
    environment:
      # 5. Хранение чувствительных данных
      - POSTGRES_PASSWORD=SuperSecretPassword
    ports:
      # 6. Открытый порт БД наружу на хост-машину
      - "5432:5432"
    # 7. Нет томов для базы данных. При перезапуске все данные из базы удалятся